language: ruby
os:
  - linux
  - osx
addons:
  homebrew:
    packages:
      - squashfs
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - squashfs-tools
      - bison
cache: bundler
before_install:
  - gem install bundler -v 1.15.1
rvm:
  - 2.4.0
install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl -L http://enclose.io/rubyc/rubyc-darwin-x64.gz | gunzip > rubyc && chmod +x rubyc; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -L http://enclose.io/rubyc/rubyc-linux-x64.gz | gunzip > rubyc && chmod +x rubyc; fi
before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mksquashfs -version; fi
  - ./rubyc -v
script:
  - ./rubyc --output 3scale exe/3scale
